export { default as Tab } from './Tab'
export { default as TabList } from './TabList'
export { default as TabPanel } from './TabPanel'
export { default as TabPanels } from './TabPanels'
export { useTabs } from './Tabs.context'
export { default as Tabs } from './Tabs'

export type { TabProps } from './Tab'
export type { TabListProps } from './TabList'
export type { TabPanelProps } from './TabPanel'
export type { TabPanelsProps } from './TabPanels'
export type { TabsProps } from './Tabs'
